apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sjjq9w3y0-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sjjq9w3y0-go 
  name: sjjq9w3y0-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sjjq9w3y0-go 
